import { Product } from "./types";

/**
 * Central product catalogue for Maithili Harvest.
 * Add / remove products here — the search & filter system updates automatically.
 */
export const products: Product[] = [
  {
    id: "1",
    slug: "pani-phuchka",
    name: "Pani Phuchka",
    category: "Phuchka",
    taste: "Spicy",
    price: 40,
    unit: "6 pcs",
    image: "/products/puchka.jpeg",
    zomatoRating: 4.8,
    swiggyRating: 4.7,
    description: "Traditional Kolkata style pani phuchka with spicy tamarind water.",
    badge: "Bestseller",
  },
  {
    id: "2",
    slug: "dahi-phuchka",
    name: "Dahi Phuchka",
    category: "Phuchka",
    taste: "Sweet",
    price: 60,
    unit: "6 pcs",
    image: "/products/papdii-chat.jpeg",
    zomatoRating: 4.9,
    swiggyRating: 4.8,
    description: "Crunchy phuchka served with creamy dahi and masala.",
    badge: null,
  },
  {
    id: "3",
    slug: "stone-ground-turmeric",
    name: "Stone-Ground Turmeric",
    category: "Spices",
    taste: "Earthy",
    price: 180,
    unit: "200g",
    image: "/products/Achar-1.webp",
    zomatoRating: 4.7,
    swiggyRating: 4.6,
    description: "Traditionally milled from single-origin Mithila rhizomes. Deep colour, earthy fragrance.",
    badge: null,
  },
  {
    id: "4",
    slug: "cold-pressed-mustard-oil",
    name: "Cold-Pressed Mustard Oil",
    category: "Oils",
    taste: "Pungent",
    price: 320,
    unit: "1 Litre",
    image: "/products/mango-achar.jpeg",
    zomatoRating: 4.8,
    swiggyRating: 4.8,
    description: "Kachi ghani extraction. Pungent, pure, and preservative-free.",
    badge: null,
  },
  {
    id: "5",
    slug: "sona-masuri-rice",
    name: "Sona Masuri Rice",
    category: "Rice & Grains",
    taste: "Mild",
    price: 140,
    unit: "1 kg",
    image: "/products/makahana.webp",
    zomatoRating: 4.6,
    swiggyRating: 4.5,
    description: "Heirloom variety grown on the Darbhanga plains. Low glycaemic, soft-cooking.",
    badge: null,
  },
  {
    id: "6",
    slug: "handmade-thekua",
    name: "Handmade Thekua",
    category: "Sweets",
    taste: "Sweet",
    price: 220,
    unit: "500g",
    image: "/products/thekua.jpg",
    zomatoRating: 4.9,
    swiggyRating: 4.9,
    description: "Festive fried wheat pastry with jaggery and fennel. Made the old way.",
    badge: "Seasonal",
  },
  {
    id: "7",
    slug: "black-cardamom-pods",
    name: "Black Cardamom Pods",
    category: "Spices",
    taste: "Smoky",
    price: 260,
    unit: "100g",
    image: "/products/Dry Fruits.jpg",
    zomatoRating: 4.7,
    swiggyRating: 4.6,
    description: "Smoked large cardamom. Intense, resinous aroma for biryanis and dals.",
    badge: null,
  },
  {
    id: "8",
    slug: "cultured-desi-ghee",
    name: "Cultured Desi Ghee",
    category: "Oils",
    taste: "Rich",
    price: 680,
    unit: "500ml",
    image: "/products/cofee.webp",
    zomatoRating: 4.9,
    swiggyRating: 4.8,
    description: "Slow-simmered from grass-fed cow milk curd. Golden, granular texture.",
    badge: "New",
  },
];
